trigger:
  branches:
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name SqlServer -Scope CurrentUser -Force'
    
- task: PowerShell@2
  inputs:
    filePath: './services/Database/ResetDB.ps1'
    arguments: '$(DatabaseUrl) $(DatabaseUsername) $(DatabasePassword)'
    workingDirectory: './services/Database'
  env:
    DATABASEURL: $(DatabaseUrl)
    DATABASEUSERNAME: $(DatabaseUsername)
    DATABASEPASSWORD: $(DatabasePassword)