trigger:

- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  displayName: Build .NET project
  steps:
  - task: PowerShell@2
    inputs:
      filePath: './services/Recipes/CreateConnectionString.ps1'
      workingDirectory: './services/Recipes'
    env:
      DATABASEURL: $(DatabaseUrl)
      DATABASEUSERNAME: $(DatabaseUsername)
      DATABASEPASSWORD: $(DatabasePassword)
  - task: PowerShell@2
    inputs:
      filePath: './services/Database/BuildMetadataAndResetDB.ps1'
      workingDirectory: './services/Database'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.fsproj'
      feedsToUse: 'select'
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      msbuildArgs: '/p:target=publish /p:v=m /p:configuration=release /p:OutputPath=$(Build.BinariesDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- deployment: VMDeploy
  dependsOn: Build
  displayName: web
  pool:
    vmImage: 'Ubuntu-18.04'
  environment:
    name: Dev
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: ExtractFiles@1
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
            destinationFolder: '$(Pipeline.Workspace)/drop/$(Build.BuildId)/'
            cleanDestinationFolder: true
        - task: SSH@0
          inputs:
            sshEndpoint: 'Recipe VM SSH'
            runOptions: 'commands'
            commands: |
              (pgrep dotnet && killall dotnet -9 -q) || true
              touch $(Pipeline.Workspace)/drop/$(Build.BuildId)/b/Suave.log;
              dotnet $(Pipeline.Workspace)/drop/$(Build.BuildId)/b/ApiLayer.dll $(LocalIpAddress) &>> $(Pipeline.Workspace)/drop/$(Build.BuildId)/b/Suave.log &
            readyTimeout: '20000'